import 'package:get_it/get_it.dart';

import '../data/database/daos/base_dao.dart';
import '../data/database/daos/medicines_dao.dart';
import '../data/database/daos/customers_dao.dart';
import '../data/database/daos/suppliers_dao.dart';
import '../data/database/daos/sales_dao.dart';
import '../data/database/daos/purchases_dao.dart';
import '../data/database/daos/returns_dao.dart';
import '../data/database/daos/sync_dao.dart';
import '../data/database/daos/inventory_dao.dart';
import '../data/database/daos/customer_ledgers_dao.dart';
import '../data/database/daos/supplier_ledgers_dao.dart';
import '../data/database/daos/users_dao.dart';
import '../data/database/daos/branches_dao.dart';
import '../data/database/daos/permissions_dao.dart';
import '../data/database/daos/medicine_units_dao.dart';
import '../data/database/daos/item_batches_dao.dart';
import '../data/database/daos/stocktaking_dao.dart';
import '../data/database/daos/stocktaking_items_dao.dart';
import '../data/database/daos/customer_groups_dao.dart';
import '../data/database/daos/supplier_customers_dao.dart';
import '../data/database/daos/quotes_dao.dart';
import '../data/database/daos/cashier_shifts_dao.dart';
import '../data/database/daos/damaged_stock_dao.dart';
import '../data/database/daos/opening_stock_dao.dart';
import '../data/database/daos/promotions_dao.dart';
import '../data/database/daos/archive_records_dao.dart';
import '../data/database/daos/app_settings_dao.dart';
import '../data/database/daos/receipt_counters_dao.dart';
import '../data/database/daos/lookups_dao.dart';
import '../data/database/daos/sales_reps_dao.dart';
import '../data/database/daos/notifications_dao.dart';
import '../data/database/daos/medicine_brands_dao.dart';
import '../data/database/daos/medicine_variants_dao.dart';
import '../data/database/daos/price_groups_dao.dart';
import '../data/database/daos/stock_transfers_dao.dart';
import '../data/database/daos/stock_adjustments_dao.dart';
import '../data/database/daos/inventory_transactions_dao.dart';
import '../data/database/daos/accounts_dao.dart';
import '../data/database/daos/journal_entries_dao.dart';
import '../data/database/daos/expenses_dao.dart';
import '../data/database/daos/party_payments_dao.dart';
import '../data/database/daos/departments_dao.dart';
import '../data/database/daos/employees_dao.dart';
import '../data/database/daos/attendance_dao.dart';
import '../data/database/daos/leaves_dao.dart';
import '../data/database/daos/payroll_dao.dart';
import '../data/database/daos/admin_roles_dao.dart';
import '../data/database/daos/admin_members_dao.dart';
import '../data/database/daos/audit_logs_dao.dart';
import '../data/database/daos/suspended_sales_dao.dart';
import '../data/database/daos/items_archive_dao.dart';
import '../data/database/daos/bulk_price_updates_dao.dart';
import '../data/database/daos/report_definitions_dao.dart';
import '../data/database/daos/task_daos.dart';
import '../data/database/drift_init.dart';

final sl = GetIt.instance;

void registerDaoDependencies() {
  _reg<BaseDao>(() => BaseDao(appDatabase));
  _reg<MedicinesDao>(() => MedicinesDao(appDatabase));
  _reg<CustomersDao>(() => CustomersDao(appDatabase));
  _reg<SuppliersDao>(() => SuppliersDao(appDatabase));
  _reg<SalesDao>(() => SalesDao(appDatabase));
  _reg<PurchasesDao>(() => PurchasesDao(appDatabase));
  _reg<ReturnsDao>(() => ReturnsDao(appDatabase));
  _reg<SyncDao>(() => SyncDao(appDatabase));
  _reg<InventoryDao>(() => InventoryDao(appDatabase));
  _reg<CustomerLedgersDao>(() => CustomerLedgersDao(appDatabase));
  _reg<SupplierLedgersDao>(() => SupplierLedgersDao(appDatabase));
  _reg<UsersDao>(() => UsersDao(appDatabase));
  _reg<BranchesDao>(() => BranchesDao(appDatabase));
  _reg<PermissionsDao>(() => PermissionsDao(appDatabase));
  _reg<MedicineUnitsDao>(() => MedicineUnitsDao(appDatabase));
  _reg<ItemBatchesDao>(() => ItemBatchesDao(appDatabase));
  _reg<StocktakingDao>(() => StocktakingDao(appDatabase));
  _reg<StocktakingItemsDao>(() => StocktakingItemsDao(appDatabase));
  _reg<CustomerGroupsDao>(() => CustomerGroupsDao(appDatabase));
  _reg<SupplierCustomersDao>(() => SupplierCustomersDao(appDatabase));
  _reg<QuotesDao>(() => QuotesDao(appDatabase));
  _reg<CashierShiftsDao>(() => CashierShiftsDao(appDatabase));
  _reg<DamagedStockDao>(() => DamagedStockDao(appDatabase));
  _reg<OpeningStockDao>(() => OpeningStockDao(appDatabase));
  _reg<PromotionsDao>(() => PromotionsDao(appDatabase));
  _reg<ArchiveRecordsDao>(() => ArchiveRecordsDao(appDatabase));
  _reg<AppSettingsDao>(() => AppSettingsDao(appDatabase));
  _reg<ReceiptCountersDao>(() => ReceiptCountersDao(appDatabase));
  _reg<LookupsDao>(() => LookupsDao(appDatabase));
  _reg<SalesRepsDao>(() => SalesRepsDao(appDatabase));
  _reg<NotificationsDao>(() => NotificationsDao(appDatabase));
  _reg<MedicineBrandsDao>(() => MedicineBrandsDao(appDatabase));
  _reg<MedicineVariantsDao>(() => MedicineVariantsDao(appDatabase));
  _reg<PriceGroupsDao>(() => PriceGroupsDao(appDatabase));
  _reg<StockTransfersDao>(() => StockTransfersDao(appDatabase));
  _reg<StockAdjustmentsDao>(() => StockAdjustmentsDao(appDatabase));
  _reg<InventoryTransactionsDao>(() => InventoryTransactionsDao(appDatabase));
  _reg<AccountsDao>(() => AccountsDao(appDatabase));
  _reg<JournalEntriesDao>(() => JournalEntriesDao(appDatabase));
  _reg<ExpensesDao>(() => ExpensesDao(appDatabase));
  _reg<PartyPaymentsDao>(() => PartyPaymentsDao(appDatabase));
  _reg<DepartmentsDao>(() => DepartmentsDao(appDatabase));
  _reg<EmployeesDao>(() => EmployeesDao(appDatabase));
  _reg<AttendanceDao>(() => AttendanceDao(appDatabase));
  _reg<LeavesDao>(() => LeavesDao(appDatabase));
  _reg<PayrollDao>(() => PayrollDao(appDatabase));
  _reg<AdminRolesDao>(() => AdminRolesDao(appDatabase));
  _reg<AdminMembersDao>(() => AdminMembersDao(appDatabase));
  _reg<AuditLogsDao>(() => AuditLogsDao(appDatabase));
  _reg<SuspendedSalesDao>(() => SuspendedSalesDao(appDatabase));
  _reg<ItemsArchiveDao>(() => ItemsArchiveDao(appDatabase));
  _reg<BulkPriceUpdatesDao>(() => BulkPriceUpdatesDao(appDatabase));
  _reg<ReportDefinitionsDao>(() => ReportDefinitionsDao(appDatabase));
  _reg<TasksDao>(() => TasksDao(appDatabase));
  _reg<NotesDao>(() => NotesDao(appDatabase));
  _reg<RemindersDao>(() => RemindersDao(appDatabase));
  _reg<MessagesDao>(() => MessagesDao(appDatabase));
}

void _reg<T extends Object>(T Function() factory) {
  if (!sl.isRegistered<T>()) {
    sl.registerLazySingleton<T>(factory);
  }
}
