import 'dart:math';
import 'package:uuid/uuid.dart';
import 'package:pharmacy_system/app/core/models/sales/sale_invoice_model.dart';
import 'package:pharmacy_system/app/core/models/purchases/purchase_invoice_model.dart';
import 'package:pharmacy_system/app/core/models/sales/invoice_return_model.dart';
import 'package:pharmacy_system/app/core/models/accounting/journal_entry_model.dart';
import 'journal_entry_service.dart';

class SalesAccountingPolicy {
  final String cashAccountId;
  final String cardAccountId;
  final String bankAccountId;
  final String walletAccountId;
  final String receivablesAccountId;
  final String salesRevenueAccountId;
  final String taxPayableAccountId;
  final String inventoryAccountId;
  final String costOfGoodsSoldAccountId;

  const SalesAccountingPolicy({
    this.cashAccountId = 'system:cash',
    this.cardAccountId = 'system:card_clearing',
    this.bankAccountId = 'system:bank',
    this.walletAccountId = 'system:mobile_wallet',
    this.receivablesAccountId = 'system:accounts_receivable',
    this.salesRevenueAccountId = 'system:sales_revenue',
    this.taxPayableAccountId = 'system:tax_payable',
    this.inventoryAccountId = 'system:inventory',
    this.costOfGoodsSoldAccountId = 'system:cost_of_goods_sold',
  });
}

class PurchaseAccountingPolicy {
  final String inventoryAccountId;
  final String accountsPayableAccountId;
  final String cashAccountId;

  const PurchaseAccountingPolicy({
    this.inventoryAccountId = 'system:inventory',
    this.accountsPayableAccountId = 'system:accounts_payable',
    this.cashAccountId = 'system:cash',
  });
}

class ReturnAccountingService {
  final SalesAccountingPolicy policy;
  ReturnAccountingService({this.policy = const SalesAccountingPolicy()});

  JournalEntryLineModel _line({
    required String accountId,
    double debit = 0,
    double credit = 0,
    String? description,
  }) {
    return JournalEntryLineModel(
      id: const Uuid().v4(),
      accountId: accountId,
      accountName: '', // Placeholder
      accountCode: '', // Placeholder
      debit: debit,
      credit: credit,
      description: description,
    );
  }

  Future<JournalEntryModel> buildSalesReturnEntry({
    required InvoiceReturnModel salesReturn,
    required String actorId,
  }) async {
    final amount = salesReturn.totalReturnAmount;
    final lines = <JournalEntryLineModel>[
      _line(
        accountId: policy.salesRevenueAccountId,
        debit: amount,
        description: 'عكس إيراد مبيعات',
      ),
      _line(
        accountId: policy.cashAccountId,
        credit: amount,
        description: 'مرتجع بيع',
      ),
    ];

    return JournalEntryModel(
      id: 'journal:sales_return:${salesReturn.id}',
      branchId: salesReturn.branchId,
      entryNumber: 0, // Should be generated by service
      entryDate: salesReturn.createdAt,
      entryType: 'salesReturn',
      referenceNumber: salesReturn.returnNumber,
      description: 'مرتجع بيع #${salesReturn.returnNumber}',
      lines: lines,
      totalDebit: amount,
      totalCredit: amount,
      createdById: actorId,
    );
  }
}

class SalesAccountingService {
  final SalesAccountingPolicy policy;
  SalesAccountingService({this.policy = const SalesAccountingPolicy()});

  JournalEntryLineModel _line({
    required String accountId,
    double debit = 0,
    double credit = 0,
    String? description,
  }) {
    return JournalEntryLineModel(
      id: const Uuid().v4(),
      accountId: accountId,
      accountName: '', // Placeholder
      accountCode: '', // Placeholder
      debit: debit,
      credit: credit,
      description: description,
    );
  }

  Future<JournalEntryModel> buildEntry({
    required SaleInvoiceModel sale,
    required String actorId,
  }) async {
    final lines = <JournalEntryLineModel>[];
    final amount = sale.finalAmount;

    lines.add(_line(
      accountId: policy.cashAccountId,
      debit: amount,
      description: 'مبيعات نقدية',
    ));

    lines.add(_line(
      accountId: policy.salesRevenueAccountId,
      credit: amount,
      description: 'إيراد مبيعات',
    ));

    return JournalEntryModel(
      id: 'journal:sale:${sale.id}',
      branchId: sale.branchId,
      entryNumber: 0,
      entryDate: sale.createdAt,
      entryType: 'sales',
      referenceNumber: sale.invoiceNumber,
      description: 'فاتورة بيع #${sale.invoiceNumber}',
      lines: lines,
      totalDebit: amount,
      totalCredit: amount,
      createdById: actorId,
    );
  }
}
