import 'package:pharmacy_system/app/core/injection.dart';
import 'package:pharmacy_system/app/core/data/database/daos/app_settings_dao.dart';
import 'package:pharmacy_system/app/core/data/repositories/medicines_repository.dart';
import 'package:pharmacy_system/app/core/data/services/auth/auth_service.dart';
import 'package:pharmacy_system/app/core/utils/app_utils.dart';

class BarcodeService {
  static const String _prefix = 'PH';
  static const int _serialLength = 5;

  static Future<int> _highestSerial() async {
    try {
      final dao = sl<AppSettingsDao>();
      final serialData = await dao.get('barcode_last_serial');
      var highest = int.tryParse(serialData?.value ?? '0') ?? 0;

      if (highest == 0) {
        final branchId = AuthService.currentBranchId ?? '';
        final repo = sl<MedicinesRepository>();
        final allMedicines = await repo.getMedicines(branchId: branchId);

        for (final medicine in allMedicines) {
          if (medicine.isDeleted) continue;

          for (final code in medicine.barcodes) {
            final serial = _extractSerial(code);
            if (serial != null && serial > highest) {
              highest = serial;
            }
          }
        }
        await dao.set('barcode_last_serial', highest.toString());
      }
      return highest;
    } catch (e, s) {
      safeDebugPrint('BarcodeService._highestSerial failed: $e\n$s');
      return 0;
    }
  }

  static int? _extractSerial(String code) {
    if (!code.startsWith(_prefix)) return null;
    try {
      final digits = code.substring(_prefix.length);
      return int.tryParse(digits);
    } catch (_) {
      return null;
    }
  }

  static Future<String> generate() async {
    try {
      final highest = await _highestSerial();
      final nextSerial = highest + 1;
      final serialStr = nextSerial.toString().padLeft(_serialLength, '0');
      final barcode = '$_prefix$serialStr';

      final dao = sl<AppSettingsDao>();
      await dao.set('barcode_last_serial', nextSerial.toString());
      return barcode;
    } catch (e, s) {
      safeDebugPrint('BarcodeService.generate failed: $e\n$s');
      rethrow;
    }
  }

  static Future<void> reserveSerial(int serial) async {
    try {
      final dao = sl<AppSettingsDao>();
      final serialData = await dao.get('barcode_last_serial');
      final current = int.tryParse(serialData?.value ?? '0') ?? 0;
      if (serial > current) {
        await dao.set('barcode_last_serial', serial.toString());
      }
    } catch (e, s) {
      safeDebugPrint('BarcodeService.reserveSerial failed: $e\n$s');
      rethrow;
    }
  }

  static Future<bool> isBarcodeTaken(String code, {String? excludeMedicineId}) async {
    try {
      final normalized = code.trim();
      if (normalized.isEmpty) return false;
      final branchId = AuthService.currentBranchId ?? '';

      final repo = sl<MedicinesRepository>();
      final allMedicines = await repo.getMedicines(branchId: branchId);

      for (final medicine in allMedicines) {
        if (medicine.isDeleted) continue;
        if (excludeMedicineId != null && medicine.id == excludeMedicineId) continue;

        for (final bc in medicine.barcodes) {
          if (bc.trim() == normalized) return true;
        }
      }
      return false;
    } catch (e, s) {
      safeDebugPrint('BarcodeService.isBarcodeTaken failed: $e\n$s');
      return false;
    }
  }

  static bool isAutoGenerated(String code) {
    try {
      return RegExp(r'^PH\d{5,}$').hasMatch(code);
    } catch (e, s) {
      safeDebugPrint('BarcodeService.isAutoGenerated failed: $e\n$s');
      return false;
    }
  }
}


